spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: Password@123
#    url: jdbc:mysql://192.168.1.3/immoc?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.1.3:3306/immoc?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell